import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation.jsx";
import SideProfile from "../components/SideProfile.jsx";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.variable} antialiased bg-gray-100 min-h-screen flex flex-col md:flex-row gap-6 p-4 pt-10`}>
        {/* Sidebar */}
        <aside className='w-full md:w-[380px]'>
          <SideProfile />
        </aside>

        {/* Main content */}
        <main className='flex-1  lg:mt-45 space-y-10'>
          <div className="block md:hidden">

          <Navigation />
          </div>
          {children}
        </main>

        {/* Bottom nav (optional) */}
        <div className='hidden md:block'>
          <Navigation />
        </div>
      </body>
    </html>
  );
}
